// <auto-generated />
namespace PickMyCropBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201801111018PM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201801111018PM));
        
        string IMigrationMetadata.Id
        {
            get { return "201901111649559_2018.01.11 10.18PM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
