// <auto-generated />
namespace PickMyCropBackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190112414PM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190112414PM));
        
        string IMigrationMetadata.Id
        {
            get { return "201901121044598_2019.01.12 4.14PM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
